version: '3'
services:
    master:
        image: hbai/mysql-master-sf
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=master_passw0rd
            - MYSQL_REPLICA_USER=replica
            - MYSQL_REPLICA_PASS=replica_Passw0rd
        deploy: 
          resources:
            limits:
              cpus: 1
              memory: 1024M
    slave:
        image: hbai/mysql-slave-sf
        restart: unless-stopped
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=slave_passw0rd
            - MYSQL_REPLICA_USER=replica
            - MYSQL_REPLICA_PASS=replica_Passw0rd
            - MYSQL_MASTER=master
            - MYSQL_MASTER_WAIT_TIME=10
            - MYSQL_MASTER_PORT=3306
            - CREATE_PET_DB=true
        deploy: 
          resources:
            limits:
              cpus: 1
              memory: 1024M
    wordpress:
        depends_on:
            - master
        image: wordpress:latest
        ports:
            - "8181:80"
        restart: always
        environment:
            - WORDPRESS_DB_HOST=master:3306
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=master_passw0rd